import {config} from 'dotenv';config({path:'.env.local'});
import {PrismaPg} from '@prisma/adapter-pg';
import {PrismaClient,VerificationState,LeadStage} from '@prisma/client';
import prospects from '../src/lib/prospects.json' with {type:'json'};
const url=new URL(process.env.DATABASE_URL!);url.searchParams.delete('sslmode');url.searchParams.delete('pgbouncer');const connectionString=url.toString();const adapter=new PrismaPg({connectionString,ssl:{rejectUnauthorized:false}});const db=new PrismaClient({adapter});
const verification=(v:string):VerificationState=>v==='Verified'?VerificationState.VERIFIED:v==='Partially Verified'?VerificationState.PARTIALLY_VERIFIED:v==='Requires Verification'?VerificationState.REQUIRES_VERIFICATION:VerificationState.UNKNOWN;
const stage=(v:string):LeadStage=>({Research:LeadStage.RESEARCH,Verified:LeadStage.VERIFIED,Qualified:LeadStage.QUALIFIED,Contacted:LeadStage.CONTACTED,Engaged:LeadStage.ENGAGED}[v]||LeadStage.RESEARCH);
async function main(){const org=await db.organization.upsert({where:{id:'00000000-0000-0000-0000-000000000001'},update:{name:'Masar'},create:{id:'00000000-0000-0000-0000-000000000001',name:'Masar'}});for(const p of prospects){const company=await db.company.upsert({where:{organizationId_prospectId:{organizationId:org.id,prospectId:p.id}},update:{name:p.name,industry:p.industry,city:p.city,verification:verification(p.confidence),confidence:p.score,lastVerifiedAt:new Date(p.verified)},create:{organizationId:org.id,prospectId:p.id,name:p.name,country:p.country,city:p.city,industry:p.industry,verification:verification(p.confidence),confidence:p.score,lastVerifiedAt:new Date(p.verified),sourceUrl:null}});await db.lead.upsert({where:{id:`10000000-0000-4000-8000-${String(Number(p.id.slice(4))).padStart(12,'0')}`},update:{score:p.score,stage:stage(p.status),priority:p.tier},create:{id:`10000000-0000-4000-8000-${String(Number(p.id.slice(4))).padStart(12,'0')}`,companyId:company.id,score:p.score,stage:stage(p.status),priority:p.tier,source:p.source,scoreExplanation:{source:'Masar 2026 research dataset',classification:p.tier}}});await db.activity.create({data:{companyId:company.id,type:'IMPORTED',summary:'Imported from verified Masar 2026 research dataset',metadata:{source:p.source}}}).catch(()=>{});}console.log(`Seeded ${prospects.length} companies and leads for ${org.name}`)}
main().finally(()=>db.$disconnect());
